apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
    spec:
      containers:
        - image: itzg/minecraft-server
          name: minecraft-server
          env:
            - name: TYPE
              value: "VANILLA"
            - name: EULA
              value: "TRUE"
          ports:
            - containerPort: 25565
              name: minecraft
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minecraft
  name: minecraft
spec:
  selector:
    app: mc
  ports:
  - name: 25565-minecract
    port: 25565
    protocol: TCP
    targetPort: minecraft
  type: LoadBalancer